"""cc-hooks: typed Python SDK and offline test runner for Claude Code hooks.

Read the event, decide, exit::

    from cc_hooks import read_event, PreToolUse, deny

    event = read_event()
    if isinstance(event, PreToolUse) and event.command and ".env" in event.command:
        deny("Secrets stay out of the transcript").exit()

Reference: https://code.claude.com/docs/en/hooks
"""

from __future__ import annotations

from .decide import (
    Decision,
    DecisionError,
    add_context,
    allow,
    ask,
    block,
    blocking_error,
    defer,
    deny,
    display,
    elicitation,
    no_decision,
    permission_request,
    retry,
    session_start,
    stop,
    system_message,
    update_input,
    update_output,
    watch_paths,
)
from .events import (
    COMMON_FIELDS,
    DOCS_FETCHED,
    DOCS_URL,
    EVENT_CLASSES,
    EVENT_NAMES,
    EVENTS,
    SCHEMA_VERSION,
    TOOL_EVENTS,
    TOOL_INPUT_FIELDS,
    ConfigChange,
    CwdChanged,
    DirectoryAdded,
    Elicitation,
    ElicitationResult,
    Event,
    EventSpec,
    FieldSpec,
    FileChanged,
    HookInputError,
    InstructionsLoaded,
    MessageDisplay,
    Notification,
    PermissionDenied,
    PermissionRequest,
    PostCompact,
    PostModelSwitch,
    PostToolBatch,
    PostToolUse,
    PostToolUseFailure,
    PreCompact,
    PreModelSwitch,
    PreToolUse,
    SessionEnd,
    SessionStart,
    Setup,
    Stop,
    StopFailure,
    SubagentStart,
    SubagentStop,
    TaskCompleted,
    TaskCreated,
    TeammateIdle,
    ToolEvent,
    UserPromptExpansion,
    UserPromptSubmit,
    WorktreeCreate,
    WorktreeRemove,
    dry_run,
    parse_event,
    read_event,
)

__version__ = "0.1.0"

__all__ = [
    "COMMON_FIELDS",
    "DOCS_FETCHED",
    "DOCS_URL",
    "EVENTS",
    "EVENT_CLASSES",
    "EVENT_NAMES",
    "SCHEMA_VERSION",
    "TOOL_EVENTS",
    "TOOL_INPUT_FIELDS",
    "ConfigChange",
    "CwdChanged",
    "Decision",
    "DecisionError",
    "DirectoryAdded",
    "Elicitation",
    "ElicitationResult",
    "Event",
    "EventSpec",
    "FieldSpec",
    "FileChanged",
    "HookInputError",
    "InstructionsLoaded",
    "MessageDisplay",
    "Notification",
    "PermissionDenied",
    "PermissionRequest",
    "PostCompact",
    "PostModelSwitch",
    "PostToolBatch",
    "PostToolUse",
    "PostToolUseFailure",
    "PreCompact",
    "PreModelSwitch",
    "PreToolUse",
    "SessionEnd",
    "SessionStart",
    "Setup",
    "Stop",
    "StopFailure",
    "SubagentStart",
    "SubagentStop",
    "TaskCompleted",
    "TaskCreated",
    "TeammateIdle",
    "ToolEvent",
    "UserPromptExpansion",
    "UserPromptSubmit",
    "WorktreeCreate",
    "WorktreeRemove",
    "__version__",
    "add_context",
    "allow",
    "ask",
    "block",
    "blocking_error",
    "defer",
    "deny",
    "display",
    "dry_run",
    "elicitation",
    "no_decision",
    "parse_event",
    "permission_request",
    "read_event",
    "retry",
    "session_start",
    "stop",
    "system_message",
    "update_input",
    "update_output",
    "watch_paths",
]
