"""The ``cc-hooks`` command line: events, explain, test, record."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from . import __version__
from .decide import (
    EXIT_2_BLOCK_EVENTS,
    PERMISSION_DECISIONS,
    Observed,
    combine,
    observe,
)
from .events import (
    COMMON_FIELDS,
    DOCS_FETCHED,
    DOCS_URL,
    EVENTS,
    TOOL_INPUT_FIELDS,
    Event,
    HookInputError,
    parse_event,
)
from .settings import Collection, Resolved, SettingsError, collect, resolve

DEFAULT_RECORD_FILE = Path("~/.cc-hooks/recorded.jsonl")
RECORD_EVENTS = ("PreToolUse", "PostToolUse")


# --------------------------------------------------------------------------- helpers


def _load_payload(path: str) -> Any:
    text = sys.stdin.read() if path == "-" else Path(path).read_text(encoding="utf-8")
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise HookInputError(f"{path}: not valid JSON: {exc}") from exc


def _event_from_payload(payload: Any, *, warnings: list[str]) -> Event:
    try:
        return parse_event(payload)
    except HookInputError as strict_error:
        event = parse_event(payload, strict=False)
        warnings.append(f"payload does not match the documented schema: {strict_error}")
        return event


def _collection(args: argparse.Namespace, event: Event | None) -> Collection:
    cwd: Path | None = None
    walk_up = True
    if getattr(args, "cwd", None):
        cwd = Path(args.cwd)
        walk_up = False
    elif event is not None and isinstance(event.cwd, str) and Path(event.cwd).is_dir():
        cwd = Path(event.cwd)
    home = Path(args.home) if getattr(args, "home", None) else None
    env = dict(os.environ)
    if getattr(args, "plugins_root", None):
        env["CLAUDE_CODE_PLUGIN_CACHE_DIR"] = args.plugins_root
    if home is not None:
        env.pop("CLAUDE_CONFIG_DIR", None)
    settings_files = [Path(p) for p in args.settings] if getattr(args, "settings", None) else None
    return collect(
        cwd,
        home=home,
        env=env,
        settings_files=settings_files,
        plugins=not getattr(args, "no_plugins", False),
        walk_up=walk_up,
    )


def _short(text: str | None, width: int = 60) -> str:
    if not text:
        return ""
    text = " ".join(text.split())
    return text if len(text) <= width else text[: width - 3] + "..."


def _display_path(path: Path) -> str:
    home = str(Path.home())
    text = str(path)
    return "~" + text[len(home) :] if text.startswith(home) else text


# --------------------------------------------------------------------------- events


def render_events_table() -> str:
    width = max(len(name) for name in EVENTS)
    lines = [f"{len(EVENTS)} hook events, from {DOCS_URL} ({DOCS_FETCHED})", ""]
    header = f"{'#':>2}  {'Event':<{width}}  {'Matcher on':<24}  {'Exit 2':<7}  Decision"
    lines.append(header)
    lines.append("-" * len(header))
    for index, spec in enumerate(EVENTS.values(), 1):
        matcher = spec.matcher_field or "(none)"
        if matcher == "file_basename":
            matcher = "basename(file_path)"
        blocks = "blocks" if spec.can_block else "no"
        lines.append(
            f"{index:>2}  {spec.name:<{width}}  {matcher:<24}  {blocks:<7}  {spec.decision}"
        )
    return "\n".join(lines)


def render_events_markdown() -> str:
    out: list[str] = []
    out.append("# Hook events")
    out.append("")
    out.append(
        f"Generated by `cc-hooks events --markdown` from the hooks reference at "
        f"<{DOCS_URL}> as read on {DOCS_FETCHED}. Do not edit by hand; run `make docs`."
    )
    out.append("")
    out.append(
        f"{len(EVENTS)} events. The matcher column is the input field Claude Code evaluates "
        "the `matcher` against; events without one run on every occurrence. The exit 2 "
        "column says whether exit code 2 blocks the action. Model identifiers in the "
        "example payloads are replaced by placeholders."
    )
    out.append("")
    out.append("## Common input fields")
    out.append("")
    out.append("| Field | Type | Required | Description |")
    out.append("| --- | --- | --- | --- |")
    for f in COMMON_FIELDS:
        out.append(f"| `{f.name}` | {f.type} | {'yes' if f.required else 'no'} | {f.description} |")
    out.append("")
    out.append("## Summary")
    out.append("")
    out.append("| # | Event | Fires when | Matcher on | Decision pattern | Exit 2 |")
    out.append("| --- | --- | --- | --- | --- | --- |")
    for index, spec in enumerate(EVENTS.values(), 1):
        matcher = f"`{spec.matcher_field}`" if spec.matcher_field else "no matcher"
        if spec.matcher_field == "file_basename":
            matcher = "basename of `file_path`"
        out.append(
            f"| {index} | [{spec.name}](#{spec.name.lower()}) | {spec.summary} | {matcher} | "
            f"{spec.decision} | {spec.exit_2} |"
        )
    out.append("")
    for spec in EVENTS.values():
        out.append(f"## {spec.name}")
        out.append("")
        out.append(f"{spec.summary}. Reference: <{spec.url}>.")
        out.append("")
        if spec.matcher_field:
            values = ", ".join(f"`{v}`" for v in spec.matcher_values)
            out.append(f"- Matcher: {spec.matcher}" + (f" ({values})" if values else ""))
        else:
            out.append("- Matcher: not supported; the hook fires on every occurrence")
        out.append(f"- Decision control: {spec.decision}")
        if spec.output_fields:
            out.append("- Output fields: " + ", ".join(f"`{f}`" for f in spec.output_fields))
        out.append(f"- Exit code 2: {spec.exit_2}")
        out.append("")
        out.append("| Field | Type | Required | Description |")
        out.append("| --- | --- | --- | --- |")
        for f in spec.fields:
            out.append(
                f"| `{f.name}` | {f.type} | {'yes' if f.required else 'no'} | {f.description} |"
            )
        out.append("")
        out.append("```json")
        out.append(json.dumps(spec.example, indent=2))
        out.append("```")
        out.append("")
    out.append("## tool_input fields of the built-in tools")
    out.append("")
    out.append(
        "From the PreToolUse section of the reference. `tool_input` for MCP tools is the "
        "tool's own argument schema."
    )
    out.append("")
    for tool, fields in TOOL_INPUT_FIELDS.items():
        out.append(f"### {tool}")
        out.append("")
        out.append("| Field | Type | Required | Description |")
        out.append("| --- | --- | --- | --- |")
        for f in fields:
            out.append(
                f"| `{f.name}` | {f.type} | {'yes' if f.required else 'no'} | {f.description} |"
            )
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def cmd_events(args: argparse.Namespace) -> int:
    if args.json:
        data = {
            "docs": DOCS_URL,
            "fetched": DOCS_FETCHED,
            "events": [
                {
                    "name": spec.name,
                    "summary": spec.summary,
                    "matcher": spec.matcher,
                    "matcher_field": spec.matcher_field,
                    "matcher_values": list(spec.matcher_values),
                    "fields": [f.__dict__ for f in spec.fields],
                    "decision": spec.decision,
                    "output_fields": list(spec.output_fields),
                    "can_block": spec.can_block,
                    "exit_2": spec.exit_2,
                    "example": spec.example,
                    "url": spec.url,
                }
                for spec in EVENTS.values()
            ],
        }
        print(json.dumps(data, indent=2))
    elif args.markdown:
        sys.stdout.write(render_events_markdown())
    else:
        print(render_events_table())
    return 0


# --------------------------------------------------------------------------- explain


def _decision_summary(event_name: str) -> list[str]:
    spec = EVENTS[event_name]
    lines = [f"decision control: {spec.decision}"]
    if spec.output_fields:
        lines.append("  fields: " + ", ".join(spec.output_fields))
    if event_name in PERMISSION_DECISIONS:
        lines.append("  precedence across hooks: " + " > ".join(PERMISSION_DECISIONS[event_name]))
    blocks = "blocks" if event_name in EXIT_2_BLOCK_EVENTS else "does not block"
    lines.append(f"exit code 2: {blocks}. {spec.exit_2}")
    return lines


def cmd_explain(args: argparse.Namespace) -> int:
    warnings: list[str] = []
    try:
        event = _event_from_payload(_load_payload(args.event), warnings=warnings)
    except (HookInputError, OSError) as exc:
        print(f"cc-hooks explain: {exc}", file=sys.stderr)
        return 2
    try:
        collection = _collection(args, event)
    except SettingsError as exc:
        print(f"cc-hooks explain: {exc}", file=sys.stderr)
        return 2
    warnings.extend(collection.warnings)
    candidates = collection.handlers_for(event.hook_event_name)
    resolved = resolve(candidates, event)
    chosen = {id(r.handler) for r in resolved}
    skipped = [h for h in candidates if id(h) not in chosen]
    spec = event.spec

    if args.json:
        print(
            json.dumps(
                {
                    "event": event.hook_event_name,
                    "matcher_value": event.matcher_value,
                    "project_root": str(collection.project_root),
                    "sources": [
                        {
                            "kind": s.label,
                            "path": str(s.path),
                            "exists": any(
                                item.source == s and item.data is not None
                                for item in collection.loaded
                            ),
                        }
                        for s in collection.sources
                    ],
                    "handlers": [
                        {
                            "source": r.handler.source.label,
                            "matcher": r.handler.matcher,
                            "type": r.handler.type,
                            "command": r.handler.resolved_command,
                            "timeout": r.handler.effective_timeout,
                            "async": r.handler.is_async,
                            "matched_by": r.matched_by,
                        }
                        for r in resolved
                    ],
                    "not_matched": [
                        {
                            "source": h.source.label,
                            "matcher": h.matcher,
                            "command": h.resolved_command,
                        }
                        for h in skipped
                    ],
                    "decision": spec.decision,
                    "output_fields": list(spec.output_fields),
                    "exit_2": spec.exit_2,
                    "can_block": spec.can_block,
                    "warnings": warnings,
                    "docs": spec.url,
                },
                indent=2,
            )
        )
        return 0

    label = event.hook_event_name
    if spec.matcher_field:
        label += f"  ({spec.matcher_field}={event.matcher_value!r})"
    print(f"cc-hooks explain: {label}")
    print(f"project root: {_display_path(collection.project_root)}")
    print("sources:")
    for item in collection.loaded:
        state = "" if item.data is not None else "  (missing)"
        print(f"  {item.source.label:<24} {_display_path(item.source.path)}{state}")
    if collection.disable_all_hooks:
        print("disableAllHooks is true: only managed hooks (if any) run")
    total = len(candidates)
    print(
        f"handlers that would run: {len(resolved)} of {total} {event.hook_event_name} "
        "handler(s); Claude Code runs them in parallel"
    )
    for index, item in enumerate(resolved, 1):
        h = item.handler
        extras = [h.type, f"timeout {h.effective_timeout:g}s"]
        if h.is_async:
            extras.append("async")
        print(f"  {index}. [{h.source.label}] {item.matched_by}; " + ", ".join(extras))
        print(f"     {h.resolved_command}")
        if h.type != "command":
            print("     (not a command hook; cc-hooks test does not execute it)")
    if skipped:
        print("not matched:")
        for h in skipped:
            print(f"  - [{h.source.label}] matcher {h.matcher!r}: {h.resolved_command}")
    for line in _decision_summary(event.hook_event_name):
        print(line)
    print(f"docs: {spec.url}")
    for warning in warnings:
        print(f"warning: {warning}")
    return 0


# --------------------------------------------------------------------------- test


@dataclass
class Fixture:
    path: Path
    event: Event
    expect: dict[str, Any]
    strict_warning: str | None = None


@dataclass
class HandlerRun:
    resolved: Resolved
    observed: Observed
    executed: bool
    exit_code: int | None = None
    stdout: str = ""
    stderr: str = ""


def _load_fixtures(paths: list[str]) -> tuple[list[Fixture], list[str]]:
    fixtures: list[Fixture] = []
    errors: list[str] = []
    files: list[Path] = []
    for raw in paths:
        path = Path(raw)
        if path.is_dir():
            files.extend(sorted(p for p in path.glob("*.json") if p.is_file()))
        elif path.is_file():
            files.append(path)
        else:
            errors.append(f"{path}: no such file or directory")
    for path in files:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            errors.append(f"{path}: {exc}")
            continue
        if not isinstance(data, dict):
            errors.append(f"{path}: fixture must be a JSON object")
            continue
        payload = data.get("event", data if "hook_event_name" in data else None)
        expect = data.get("expect", {})
        if payload is None or not isinstance(expect, dict):
            errors.append(f"{path}: fixture needs an 'event' object and an 'expect' object")
            continue
        warnings: list[str] = []
        try:
            event = _event_from_payload(payload, warnings=warnings)
        except HookInputError as exc:
            errors.append(f"{path}: {exc}")
            continue
        fixtures.append(Fixture(path, event, expect, warnings[0] if warnings else None))
    return fixtures, errors


def _run_handler(
    item: Resolved, event: Event, *, project: Path, dry_run: bool, max_timeout: float
) -> HandlerRun:
    handler = item.handler
    if handler.type != "command":
        observed = Observed("none", note=f"{handler.type} hook not executed")
        return HandlerRun(item, observed, executed=False)
    env = dict(os.environ)
    env["CLAUDE_PROJECT_DIR"] = str(project)
    if dry_run:
        env["CC_HOOKS_DRY_RUN"] = "1"
    else:
        env.pop("CC_HOOKS_DRY_RUN", None)
    if handler.source.plugin_root is not None:
        env["CLAUDE_PLUGIN_ROOT"] = str(handler.source.plugin_root)
    cwd = event.cwd if isinstance(event.cwd, str) and Path(event.cwd).is_dir() else str(project)
    timeout = min(handler.effective_timeout, max_timeout)
    payload = event.to_json()
    try:
        argv = handler.exec_argv
        if argv:
            proc = subprocess.run(
                argv,
                input=payload,
                capture_output=True,
                text=True,
                timeout=timeout,
                cwd=cwd,
                env=env,
            )
        else:
            proc = subprocess.run(
                handler.command or "",
                shell=True,
                input=payload,
                capture_output=True,
                text=True,
                timeout=timeout,
                cwd=cwd,
                env=env,
            )
    except FileNotFoundError as exc:
        observed = Observed("error", exit_code=127, note=f"cannot start: {exc}")
        return HandlerRun(item, observed, executed=True, exit_code=127, stderr=str(exc))
    except subprocess.TimeoutExpired:
        note = f"timed out after {timeout:g}s; Claude Code discards the output (no decision)"
        if handler.event == "PreModelSwitch":
            note = f"timed out after {timeout:g}s; on PreModelSwitch a timeout blocks the switch"
            return HandlerRun(item, Observed("deny", note=note), executed=True)
        return HandlerRun(item, Observed("timeout", note=note), executed=True)
    observed = observe(event.hook_event_name, proc.stdout, proc.returncode, proc.stderr)
    return HandlerRun(item, observed, True, proc.returncode, proc.stdout, proc.stderr)


def _check_expectation(
    expect: dict[str, Any], combined: Observed, runs: list[HandlerRun]
) -> list[str]:
    failures: list[str] = []
    if "decision" in expect:
        wanted = str(expect["decision"])
        if combined.kind != wanted:
            failures.append(f"decision {combined.kind}, expected {wanted}")
    if "reason_contains" in expect:
        needle = str(expect["reason_contains"]).lower()
        if needle not in (combined.reason or "").lower():
            failures.append(f"reason {_short(combined.reason, 40)!r} lacks {needle!r}")
    if "context_contains" in expect:
        needle = str(expect["context_contains"]).lower()
        if needle not in "\n".join(combined.context).lower():
            failures.append(f"additionalContext lacks {expect['context_contains']!r}")
    if "handlers" in expect:
        wanted_count = int(expect["handlers"])
        if len(runs) != wanted_count:
            failures.append(f"{len(runs)} handler(s) matched, expected {wanted_count}")
    if "exit_code" in expect:
        codes = [run.exit_code for run in runs if run.executed]
        if int(expect["exit_code"]) not in codes:
            failures.append(f"no handler exited {expect['exit_code']} (got {codes})")
    return failures


def cmd_test(args: argparse.Namespace) -> int:
    fixtures, errors = _load_fixtures(args.paths)
    for error in errors:
        print(f"error: {error}")
    if not fixtures:
        print("cc-hooks test: no fixtures found")
        return 1
    try:
        collection = _collection(args, fixtures[0].event)
    except SettingsError as exc:
        print(f"cc-hooks test: {exc}", file=sys.stderr)
        return 2
    mode = "would execute only" if args.no_run else ("exec" if args.exec else "dry run")
    if mode == "dry run":
        mode += " (CC_HOOKS_DRY_RUN=1)"
    sources = ", ".join(_display_path(s.path) for s in collection.sources if s.kind != "managed")
    print(f"cc-hooks test: {len(fixtures)} fixture(s), {mode}")
    print(f"project root: {_display_path(collection.project_root)}")
    if args.settings:
        print(f"settings: {sources}")
    for warning in collection.warnings:
        print(f"warning: {warning}")
    width = max(len(f.path.name) for f in fixtures)
    failed = 0
    results: list[dict[str, Any]] = []
    for fixture in fixtures:
        event = fixture.event
        resolved = resolve(collection.handlers_for(event.hook_event_name), event)
        runs: list[HandlerRun] = []
        for item in resolved:
            if args.no_run:
                runs.append(HandlerRun(item, Observed("none", note="not executed"), False))
            else:
                runs.append(
                    _run_handler(
                        item,
                        event,
                        project=collection.project_root,
                        dry_run=not args.exec,
                        max_timeout=args.timeout,
                    )
                )
        combined = combine([run.observed for run in runs], event.hook_event_name)
        expect = fixture.expect
        if args.no_run:
            expect = {k: v for k, v in expect.items() if k == "handlers"}
        failures = _check_expectation(expect, combined, runs)
        status = "PASS" if not failures else "FAIL"
        if args.no_run and "handlers" not in expect:
            status = "DRY"
        failed += status == "FAIL"
        reason = f'  reason="{_short(combined.reason, 48)}"' if combined.reason else ""
        print(
            f"{status}  {fixture.path.name:<{width}}  {event.hook_event_name:<18} "
            f"handlers={len(runs)}  decision={combined.kind}{reason}"
        )
        for failure in failures:
            print(f"      expected: {failure}")
        if fixture.strict_warning:
            print(f"      warning: {fixture.strict_warning}")
        for index, run in enumerate(runs, 1):
            h = run.resolved.handler
            if args.no_run or (not run.executed):
                print(f"      {index}. [{h.source.label}] would execute: {h.resolved_command}")
                continue
            detail = f"exit {run.exit_code}" if run.exit_code is not None else "no exit"
            detail += f", {run.observed.kind}"
            if run.observed.reason:
                detail += f' "{_short(run.observed.reason, 48)}"'
            if run.observed.note and (
                args.verbose or failures or run.observed.kind in ("error", "timeout")
            ):
                detail += f" ({run.observed.note})"
            print(f"      {index}. [{h.source.label}] {_short(h.resolved_command, 56)}: {detail}")
            if args.verbose and run.stderr.strip():
                print("         stderr: " + _short(run.stderr, 70))
        results.append(
            {
                "fixture": str(fixture.path),
                "event": event.hook_event_name,
                "status": status,
                "decision": combined.kind,
                "reason": combined.reason,
                "handlers": len(runs),
                "failures": failures,
            }
        )
    passed = sum(1 for r in results if r["status"] == "PASS")
    dry = sum(1 for r in results if r["status"] == "DRY")
    summary = f"summary: {passed} passed, {failed} failed"
    if dry:
        summary += f", {dry} not executed"
    print(summary)
    if args.report:
        Path(args.report).write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
    return 1 if failed or errors else 0


# --------------------------------------------------------------------------- record


def _record_handler(record_file: Path) -> dict[str, Any]:
    executable = shutil.which("cc-hooks") or "cc-hooks"
    return {
        "type": "command",
        "command": executable,
        "args": ["record", "--append", str(record_file)],
        "timeout": 5,
        "statusMessage": "cc-hooks: recording hook payload",
    }


def _is_record_handler(entry: Any) -> bool:
    if not isinstance(entry, dict):
        return False
    args = entry.get("args")
    command = str(entry.get("command", ""))
    return (
        isinstance(args, list)
        and len(args) >= 2
        and args[0] == "record"
        and args[1] == "--append"
        and os.path.basename(command) in ("cc-hooks", "cc-hooks.exe")
    )


def _settings_target(args: argparse.Namespace) -> Path:
    if args.file:
        return Path(args.file)
    from .settings import config_dir, project_root

    if args.scope == "user":
        return config_dir(Path(args.home) if args.home else None) / "settings.json"
    root = project_root(Path(args.cwd) if args.cwd else Path.cwd())
    name = "settings.json" if args.scope == "project" else "settings.local.json"
    return root / ".claude" / name


def cmd_record(args: argparse.Namespace) -> int:
    if args.append is not None:
        return _record_append(args.append)
    if args.to:
        return _record_to(args)
    target = _settings_target(args)
    data: dict[str, Any] = {}
    if target.is_file():
        try:
            data = json.loads(target.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            print(f"cc-hooks record: {target}: invalid JSON: {exc}", file=sys.stderr)
            return 2
        if not isinstance(data, dict):
            print(f"cc-hooks record: {target}: top level must be an object", file=sys.stderr)
            return 2
    hooks = data.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        print(f"cc-hooks record: {target}: 'hooks' must be an object", file=sys.stderr)
        return 2
    events = [e.strip() for e in args.events.split(",") if e.strip()]
    unknown = [e for e in events if e not in EVENTS]
    if unknown:
        print(f"cc-hooks record: unknown event(s): {', '.join(unknown)}", file=sys.stderr)
        return 2
    if args.uninstall:
        removed = 0
        for event in list(hooks):
            groups = hooks.get(event)
            if not isinstance(groups, list):
                continue
            kept_groups = []
            for group in groups:
                if isinstance(group, dict) and isinstance(group.get("hooks"), list):
                    before = len(group["hooks"])
                    group["hooks"] = [h for h in group["hooks"] if not _is_record_handler(h)]
                    removed += before - len(group["hooks"])
                    if not group["hooks"]:
                        continue
                kept_groups.append(group)
            if kept_groups:
                hooks[event] = kept_groups
            else:
                del hooks[event]
        if not hooks:
            del data["hooks"]
        target.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
        print(f"removed {removed} record handler(s) from {_display_path(target)}")
        return 0
    record_file = (
        Path(args.record_file).expanduser()
        if args.record_file
        else DEFAULT_RECORD_FILE.expanduser()
    )
    handler = _record_handler(record_file)
    added = 0
    for event in events:
        groups = hooks.setdefault(event, [])
        if not isinstance(groups, list):
            print(f"cc-hooks record: {target}: hooks.{event} must be a list", file=sys.stderr)
            return 2
        present = any(
            isinstance(g, dict)
            and any(_is_record_handler(h) for h in g.get("hooks", []) if isinstance(h, dict))
            for g in groups
        )
        if present:
            continue
        groups.append({"hooks": [handler]})
        added += 1
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(
        f"installed record handler on {', '.join(events)} in {_display_path(target)} "
        f"({added} added)"
    )
    print(f"payloads will be appended to {_display_path(record_file)}")
    print("convert them with: cc-hooks record --to fixtures/")
    return 0


def _record_append(path_text: str) -> int:
    """The installed hook: append the raw payload and never fail the tool call."""
    try:
        path = Path(path_text).expanduser() if path_text else DEFAULT_RECORD_FILE.expanduser()
        text = sys.stdin.read()
        now = dt.datetime.now(dt.UTC).isoformat(timespec="seconds")
        try:
            entry: dict[str, Any] = {"recorded_at": now, "event": json.loads(text)}
        except json.JSONDecodeError:
            entry = {"recorded_at": now, "raw": text}
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(entry) + "\n")
    except Exception as exc:
        print(f"cc-hooks record: {exc}", file=sys.stderr)
    return 0


def _record_to(args: argparse.Namespace) -> int:
    source = (
        Path(args.from_file).expanduser() if args.from_file else DEFAULT_RECORD_FILE.expanduser()
    )
    if not source.is_file():
        print(f"cc-hooks record: nothing recorded at {_display_path(source)}", file=sys.stderr)
        return 1
    out_dir = Path(args.to)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = 0
    skipped = 0
    existing = len(list(out_dir.glob("*.json")))
    for line in source.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            skipped += 1
            continue
        payload = entry.get("event") if isinstance(entry, dict) else None
        if not isinstance(payload, dict) or not isinstance(payload.get("hook_event_name"), str):
            skipped += 1
            continue
        name = payload["hook_event_name"]
        tool = payload.get("tool_name")
        suffix = f"-{tool}" if isinstance(tool, str) else ""
        safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in f"{name}{suffix}")
        index = existing + written + 1
        target = out_dir / f"{index:03d}-{safe}.json"
        fixture = {
            "event": payload,
            "expect": {"decision": "none"},
            "recorded_at": entry.get("recorded_at"),
            "note": "Edit expect.decision to what your hooks should return for this payload.",
        }
        target.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
        written += 1
    print(f"wrote {written} fixture(s) to {out_dir}" + (f", skipped {skipped}" if skipped else ""))
    return 0


# --------------------------------------------------------------------------- parser


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="cc-hooks",
        description=(
            "Explain, test and record Claude Code hooks without running anything destructive."
        ),
    )
    parser.add_argument("--version", action="version", version=f"cc-hooks {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    p_events = sub.add_parser("events", help="list the documented hook events")
    p_events.add_argument(
        "--json", action="store_true", help="print the full event registry as JSON"
    )
    p_events.add_argument("--markdown", action="store_true", help="print docs/events.md")
    p_events.set_defaults(func=cmd_events)

    def add_settings_options(p: argparse.ArgumentParser) -> None:
        p.add_argument(
            "--cwd",
            help=(
                "the directory the session started in, used as-is (default: the nearest "
                ".claude/ or .git above the event's cwd, else above the current directory)"
            ),
        )
        p.add_argument("--home", help="home directory holding .claude/ (default: your home)")
        p.add_argument(
            "--settings",
            action="append",
            metavar="FILE",
            help="use only this settings file (repeatable); skips user, managed and plugin hooks",
        )
        p.add_argument("--plugins-root", help="plugins directory (default: <config dir>/plugins)")
        p.add_argument("--no-plugins", action="store_true", help="ignore plugin hooks")

    p_explain = sub.add_parser("explain", help="which handlers would run for an event payload")
    p_explain.add_argument("event", help="path to a hook payload JSON file, or - for stdin")
    add_settings_options(p_explain)
    p_explain.add_argument("--json", action="store_true", help="machine-readable output")
    p_explain.set_defaults(func=cmd_explain)

    p_test = sub.add_parser("test", help="replay fixtures through matching command hooks")
    p_test.add_argument("paths", nargs="+", help="fixture files or directories of *.json")
    add_settings_options(p_test)
    p_test.add_argument(
        "--exec",
        action="store_true",
        help="run hooks without CC_HOOKS_DRY_RUN=1 (real side effects)",
    )
    p_test.add_argument("--no-run", action="store_true", help="only print what would execute")
    p_test.add_argument("--timeout", type=float, default=30.0, help="cap per hook, seconds (30)")
    p_test.add_argument("--report", metavar="FILE", help="write results as JSON")
    p_test.add_argument("-v", "--verbose", action="store_true", help="show notes and stderr")
    p_test.set_defaults(func=cmd_test)

    p_record = sub.add_parser("record", help="capture real payloads as fixtures")
    group = p_record.add_mutually_exclusive_group(required=True)
    group.add_argument("--install", action="store_true", help="add the recording handlers")
    group.add_argument("--uninstall", action="store_true", help="remove the recording handlers")
    group.add_argument(
        "--append", nargs="?", const="", metavar="FILE", help="(the hook) append stdin"
    )
    group.add_argument("--to", metavar="DIR", help="convert recorded payloads into fixtures")
    p_record.add_argument("--scope", choices=("user", "project", "local"), default="local")
    p_record.add_argument("--file", help="settings file to edit (overrides --scope)")
    p_record.add_argument("--events", default=",".join(RECORD_EVENTS), help="events to record")
    p_record.add_argument("--record-file", help=f"where payloads go ({DEFAULT_RECORD_FILE})")
    p_record.add_argument("--from", dest="from_file", help="recorded file to convert")
    p_record.add_argument("--cwd")
    p_record.add_argument("--home")
    p_record.set_defaults(func=cmd_record)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
